name: CD

on:
  pull_request
  # outputs:
  #   DOCKER_IMAGE_DIGEST:
  #     description: 'Digest of the pushed docker image.'
  #     value: ${{ jobs.build.outputs.DOCKER_IMAGE_DIGEST }}
  #   DOCKER_IMAGE_VERSION:
  #     description: 'Version label of the pushed docker image.'
  #     value: ${{ jobs.build.outputs.DOCKER_IMAGE_VERSION }}

env:
  GCP_SERVICE_ACCOUNT: image-pusher@artifacts-371007.iam.gserviceaccount.com
  DOCKER_REGISTRY: europe-west4-docker.pkg.dev
  DOCKER_IMAGE: europe-west4-docker.pkg.dev/artifacts-371007/iluvcoffee/docker_image
  PROJECT_ID: artifacts-371007

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # with:
        #   ref: ${{ inputs.git_ref }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'nestjs-iluvcoffee' #Must be unique in Heroku
          heroku_email: 'marxhermann@web.de'
