name: Docker Build

on:
  workflow_call:
    outputs:
      DOCKER_IMAGE_DIGEST:
        description: 'Digest of the pushed docker image.'
        value: ${{ jobs.build.outputs.DOCKER_IMAGE_DIGEST }}
      DOCKER_IMAGE_VERSION:
        description: 'Version label of the pushed docker image.'
        value: ${{ jobs.build.outputs.DOCKER_IMAGE_VERSION }}

env:
  GCP_SERVICE_ACCOUNT: image-pusher@artifacts-371007.iam.gserviceaccount.com
  DOCKER_REGISTRY: europe-west4-docker.pkg.dev
  DOCKER_IMAGE: europe-west4-docker.pkg.dev/artifacts-371007/iluvcoffee/docker_image
  PROJECT_ID: artifacts-371007

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git_ref }}

      - name: Authenticate to Google Cloud
        id: auth
      - uses: google-github-actions/setup-gcloud@master
      with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        id: docker
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
    outputs:
      DOCKER_IMAGE_DIGEST: ${{ steps.docker.outputs.digest }}
      DOCKER_IMAGE_VERSION: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
